version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      next:
        patterns:
          - next
          - react
          - react-dom
          - "@types/react"
          - "@types/react-dom"
      testing:
        patterns:
          - jest
          - jest-environment-jsdom
          - "@jest/*"
          - "@testing-library/*"
      tailwind:
        patterns:
          - tailwindcss
          - "@tailwindcss/*"
      typescript:
        patterns:
          - typescript
          - "@types/node"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns:
          - "*"
